name: ASP.NET MVC App deploy to Azure App service

on: [push,pull_request]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master  
    
    # Install Nuget
    - name: Install Nuget
      run: curl https://dist.nuget.org/win-x86-commandline/v5.3.0/nuget.exe -o nuget.exe
      
    # Nuget restore
    - name: Use NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore
      
    # dotnet msbuild and publish
    - name: msBuild with dotnet
      run: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe -p:DeployOnBuild=true -p:WebPublishMethod=Package -p:PackageAsSingleFile=true -p:SkipInvalidConfigurations=true -p:Configuration=Release
      
    # dotnet build and publish
    #- name: Build with dotnet
    #  run: dotnet build --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o myapp
        
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: dotnetappGH # Replace with your app name
        publish-profile: ${{ secrets.azureWebAppPublishProfile }} # Define secret variable in repository settings as per action documentation
        package: './myapp'
